name: gen_timeseries
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - hydra-core
      - tqdm
      - wandb
      - pre-commit
      - black
      - scikit-learn
      - torch
      - torchvision
      - torcheval
      - torchmetrics
